Missed block task
openbitlab/srvcheck pull request #19
Opened 2022-05-04 20:24 UTC by AlessandroPaparella

Implemented:

1. check
2. rpc call for signatures

2022-05-04 20:36 UTC, Luigi21 commented on srvcheck/chains/tendermint.py
> +from typing_extensions import Self
This import should be removed

2022-05-04 20:37 UTC, Lu191 commented on srvcheck/chains/tendermint.py
> +from typing_extensions import Self
This import should be removed, it's probably a type

2022-05-04 20:40 UTC, Lu191 commented on srvcheck/chains/tendermint.py
> +BLOCK_WINDOW = 100
We have these params in the config file, I think we should remove these two vars and use those from the config, so the user can change them

2022-05-04 20:45 UTC, Lu191 requested changes

2022-05-04 20:45 UTC, Lu191 commented on srvcheck/chains/tendermint.py
> +		self.TASKS += TaskTendermintBlockMissed
I guess that also this task should be performed only when the validator is in the active set (it should be used like TaskTendermintPositionChanged task, so when `isStaking()` is **True**)

2022-05-05 09:04 UTC, AlessandroPaparella commented on srvcheck/chains/tendermint.py
> +BLOCK_WINDOW = 100
Read from config file and saved as attribute in task object.

2022-05-09 11:14 UTC, dakk commented on srvcheck/chains/tendermint.py
> +			self.chain.getHealth()
Non dovrebbe restituire sempre qualcosa di valido? Mi aspettavo che semplicemente se c'e' qualche problema, l'array degli errori viene popolato

2022-05-09 11:41 UTC, Lu191 commented on srvcheck/chains/tendermint.py
> +			self.chain.getHealth()
No, la nostra funzione wrapper per le chiamate rpc ci restituisce sempre `['result']` mentre in questo caso questo metodo restituisce come risposta un oggetto che invece della proprietà `result` ha la proprietà `error` ([health method](https://docs.tendermint.com/master/rpc/#/Info/health))

2022-05-09 12:19 UTC, dakk commented on srvcheck/chains/tendermint.py
> +			self.chain.getHealth()
Chiaro (y)

2022-05-09 12:20 UTC, dakk commented on srvcheck/chains/tendermint.py
> +		self.TASKS += TaskTendermintBlockMissed
Things can change after initialization, I think it's better to check isStaking in every run() call

2022-05-09 12:28 UTC, dakk commented on srvcheck/notification/notification.py
> +	START_EMOJI = "\U0001F514"
Why we're doing this? Isn't better to directly paste emoji?

2022-05-09 13:18 UTC, Lu191 commented on srvcheck/notification/notification.py
> +	START_EMOJI = "\U0001F514"
I didn't try to paste directly the emoji, I don't know if it will work, I used Unicode due to possible compatibility issues

2022-05-09 13:20 UTC, merged