task autoupdater, disabled in conf
openbitlab/srvcheck pull request #34
Opened 2022-05-10 18:43 UTC by AlessandroPaparella

Closes #26

2022-05-11 12:27 UTC, dakk requested changes

2022-05-11 12:27 UTC, dakk commented on srvcheck/tasks/taskautoupdater.py
> +            Bash('pip install --upgrade git+https://github.com/openbitlab/srvcheck')
Doing this we install the latest commit: we need instead to specifiy the tag to install using @tagname suffix (ie: 'git+https://github.com/openbitlab/srvcheck@v0.1')

2022-05-13 10:01 UTC, franz-ops reviewed
"import subprocess" in taskautoupdater.py can be deleted

2022-05-13 10:02 UTC, dakk requested changes

2022-05-13 10:02 UTC, dakk commented on srvcheck/tasks/taskautoupdater.py
> +        nTag = requests.get('https://api.github.com/repos/openbitlab/srvcheck/git/refs/tags').json()[-1]['ref'].split('/')[-1].split('v')[1]
```[1:]```

2022-05-13 10:11 UTC, dakk commented on srvcheck/tasks/taskautoupdater.py
> +        nTag = requests.get('https://api.github.com/repos/openbitlab/srvcheck/git/refs/tags').json()[-1]['ref'].split('/')[-1].split('v')[1]
se riesci, ristabilisci i test che falliscono

2022-05-13 10:12 UTC, dakk commented on srvcheck/tasks/taskautoupdater.py
> +        nTag = requests.get('https://api.github.com/repos/openbitlab/srvcheck/git/refs/tags').json()[-1]['ref'].split('/')[-1].split('v')[1]
also fix failing tests

2022-05-13 10:26 UTC, AlessandroPaparella commented
> "import subprocess" in taskautoupdater.py can be deleted

done

2022-05-13 10:46 UTC, AlessandroPaparella commented on srvcheck/tasks/taskautoupdater.py
> +        nTag = requests.get('https://api.github.com/repos/openbitlab/srvcheck/git/refs/tags').json()[-1]['ref'].split('/')[-1].split('v')[1]
> also fix failing tests

solved

2022-05-13 11:02 UTC, merged