TaskTendermintNewProposal
openbitlab/srvcheck pull request #38
Opened 2022-05-16 15:41 UTC by AlessandroPaparella

2022-05-17 07:59 UTC, dakk requested changes

2022-05-17 07:59 UTC, dakk commented on srvcheck/chains/tendermint.py
> +			self.TASKS.append(TaskTendermintNewProposal)
We need to move this if in TaskTendermintNewProposal.isPluggable()

2022-05-17 07:59 UTC, dakk commented on tests/task_tendermint_test.py
> +        t.prev = """{"proposals":[{"proposal_id":"3","content":{"@type":"/ibc.core.client.v1.ClientUpdateProposal","title":"Upgrade IBC client","description":"Upgrade the expired client to an active
use the json value directly without parsing

2022-05-17 09:12 UTC, Lu191 requested changes

2022-05-17 09:12 UTC, Lu191 commented on install.sh
> + -c  --cmd <ledger application> command or absolute path to tendermint ledger application, used to query governance proposal"
I guess we could get the `cmd` directly reading the service file passed by the user (that is a required param), so we can remove this parameter (_**-c**_ and/or _**--cmd**_)

2022-05-17 10:35 UTC, dakk commented
A rebase from master is needed

2022-05-17 11:35 UTC, AlessandroPaparella commented on install.sh
> + -c  --cmd <ledger application> command or absolute path to tendermint ledger application, used to query governance proposal"
Ok, but we still need the flag in order to enable checks on governance proposals, since not all tendermint chains have gov module

2022-05-18 07:59 UTC, Lu191 commented on srvcheck/chains/tendermint.py
> +			return self.notify(" got new proposal: "+ nProposal["content"]["title"])
Add emoji

2022-05-18 08:01 UTC, Lu191 commented on srvcheck/chains/tendermint.py
> +		return json.loads(Bash(cmd+" q gov proposal --reverse --limit 1 --output json").stdout)["proposals"][0]
I think here you should use `.value()` method of the Bash object instead of `.stdout` attribute

2022-05-18 08:06 UTC, Lu191 requested changes

2022-05-18 08:06 UTC, Lu191 commented on install.sh
> +            sed -r 's/(.TaskTendermintNewProposal?;|.TaskTendermintNewProposal?;?$)//' $config_file #enable checks on tendermint governance module
You can also use a boolean var, for example, `enable_gov`, and then do the sed command in the `install_monitor` function like for the other parameters

2022-05-18 12:54 UTC, dakk approved these changes

2022-05-18 14:22 UTC, Lu191 requested changes

2022-05-18 14:30 UTC, Lu191 approved these changes

2022-05-18 14:37 UTC, merged