Bug fixes
openbitlab/srvcheck pull request #51
Opened 2022-05-19 18:06 UTC by Lu191

Fixed bugs:
- Fixed logic bug with `--gov` parameter
- Fixed tendermint custom task `TaskTendermintBlockMissed`
- Fixed tendermint custom task `TaskTendermintPositionChanged` output

Added stack trace to Task errors (close #48 )

2022-05-19 18:42 UTC, franz-ops approved these changes

2022-05-20 06:57 UTC, dakk commented on srvcheck/chains/tendermint.py
> +	def __init__(self, conf, notification, system, chain, checkEvery=10, notifyEvery=0):
This value will check every 10 seconds, is it mandatory a frequency like this?

2022-05-20 06:57 UTC, dakk commented on srvcheck/chains/tendermint.py
> +		self.BLOCK_WINDOW = 100 if conf["chain"]["blockWindow"] == '' else int(conf["chain"]["blockWindow"])
This is ok if blockWindow is in the conf, but fail otherwise. We need an utility function like that. I'll open a new issue.

```python 
def conf_get_or_default (conf, key, default=None)
```

2022-05-20 07:05 UTC, dakk commented on srvcheck/chains/tendermint.py
> +		self.BLOCK_WINDOW = 100 if conf["chain"]["blockWindow"] == '' else int(conf["chain"]["blockWindow"])
https://github.com/openbitlab/srvcheck/issues/52

2022-05-20 08:56 UTC, dakk requested changes

2022-05-20 08:56 UTC, dakk commented on srvcheck/utils/misc.py
> +def confGetOrDefault (conf, key, default=None):
Write a test case for this

2022-05-20 09:20 UTC, AlessandroPaparella commented
close #53

2022-05-20 09:54 UTC, dakk approved these changes

2022-05-20 09:55 UTC, merged