Conf set exp
openbitlab/srvcheck pull request #58
Opened 2022-05-24 09:30 UTC by dakk

2022-05-25 09:50 UTC, AlessandroPaparella approved these changes

2022-05-25 14:51 UTC, Lu191 requested changes
In the file **`main.py`** there is a function called **`addTasks()`** I guess it should be changed:
```
if 'disabled' in config['tasks'] and config['tasks']['disabled'].find(task.name) != -1:
```
Here we use the old way to check if a conf param exists and also to get the value of it

2022-05-27 07:55 UTC, dakk commented on srvcheck/chains/tendermint.py
> +		self.ACTIVE_SET = self.conf.getOrDefault('chain.activeSet')
Problem was here:
```python
ConfSet.addItem(ConfItem('chain.activeSet', None, None, 'active set of validators'))
```

We can't set a cast to None; fixed

2022-05-27 07:57 UTC, dakk commented on srvcheck/chains/chain.py
>          if gh_repo:
Fixed; if the value is None, cast is not performed

2022-05-31 11:01 UTC, franz-ops approved these changes

2022-05-31 11:03 UTC, merged