Issue#69
openbitlab/srvcheck pull request #79
Opened 2022-06-29 14:52 UTC by AlessandroPaparella

- Check if there is the "parachain-id" param in service file 
- Check on "relayParentNumber" from "getBlock" rpc method every 30s

2022-06-29 16:18 UTC, Lu191 commented
I don't know if checking the `--collator` flag is the right way to identify that a specific node runs a parachain.
For example, from astar [docs](https://docs.astar.network/maintain/node-commands) `--validator` and `--collator` flags seems to behave in the same way

2022-07-02 08:42 UTC, Lu191 commented on srvcheck/chains/substrate.py
> +			return self.notify(f'Relay is stuck at block {self.prev} {Emoji.Stuck}')
Please remove capital letter from `Relay` it should be `relay`

2022-07-02 08:46 UTC, Lu191 requested changes

2022-07-02 08:46 UTC, Lu191 commented on srvcheck/chains/substrate.py
> +		service = conf.getOrDefault('chain.service')
Is not possible to make a function called **`isParachain`**, it should be useful later on, when we'll implement tasks to check block production

2022-07-06 07:08 UTC, dakk reviewed
In mangata we have --collator and this will fail; can't we check for both with an or?

You can use queries; since Chain is already instantiated when addTasks is called, we can pass chain to isPluggable.

2022-07-06 12:49 UTC, AlessandroPaparella commented
> In mangata we have --collator and this check will fail, right? can't we check for both with an or?
> 
> You can use queries; since Chain is already instantiated when addTasks is called, we can pass chain to isPluggable.

I was thinking that parachain-id was mandatory, so we can check for both collator and validator or make a code refactor in order to add chain to isPluggable...

2022-07-06 12:55 UTC, dakk commented
> I was thinking that parachain-id was mandatory, so we can check for both collator and validator or make a code refactor in order to add chain to isPluggable...

I prefer the second solution

2022-07-06 14:13 UTC, dakk approved these changes

2022-07-06 14:42 UTC, merged