version compare with with packaging.version
openbitlab/srvcheck pull request #95
Opened 2022-07-20 12:54 UTC by AlessandroPaparella

close #94

2022-07-20 13:19 UTC, dakk requested changes
Can you please create at least one test case for versionCompare?

2022-07-20 13:56 UTC, AlessandroPaparella commented
> Can you please create at least one test case for versionCompare?

Added some tests with pre-release

2022-07-21 08:36 UTC, Lu191 commented
Please fix also `TaskAutoUpdater` to use the same package instead of `versionCompare()`

2022-07-21 09:33 UTC, Lu191 approved these changes

2022-07-21 09:34 UTC, merged